<?php

/**
 * @file
 * Contains migate_manager.module.
 */

use Consolidation\SiteAlias\SiteAliasManager;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\migrate\MigrateMessage;
use Drupal\migrate\Plugin\MigrationInterface;
use Drush\Drush;

/**
 * Implements hook_help().
 */
function migrate_cs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migate_manager module.
    case 'help.page.migrate_cs':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Run migrations at cron with drush flag options') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 */
function migrate_cs_cron() {
  $configOptions = Drupal::config('migrate_cs.options');
  $aliasManager = Drush::service('site.alias.manager');
  $pluginManager = Drupal::service('plugin.manager.migration');
  $migrations = $pluginManager->getDefinitions();

  $time = \Drupal::time()->getRequestTime();

  foreach ($migrations as $id => $migration) {
    $migrationCS = $configOptions->get("{$id}_cs");

    if ($migrationCS) {
      $lastRun = \Drupal::state()->get('migrate_cs.last_run.' . $id, 0);
      $setInterval = $configOptions->get("{$id}_interval") ? $configOptions->get("{$id}_interval") : 0;

      $interval = $time - $lastRun;

      if ($interval >= $setInterval) {
        $args = [$id];
        $flag = $configOptions->get("{$id}_type") ? $configOptions->get("{$id}_type") : 'normal';

        if ($flag == 'update') {
          $args[] = '--update';
        }
        elseif ($flag == 'delete') {
          $args[] = '--delete';
        }

        $process = Drush::drush($aliasManager->getSelf(), 'migrate:import', $args);
        $process->run();

        Drupal::state()->set('migrate_cs.last_run.' . $id, $time);
      }
    }
  }
}
