<?php

/**
 * @file
 * Module file for pager.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Routing\CurrentRouteMatch;

/**
 * Implements hook_help().
 */
function pager_help($route_name, CurrentRouteMatch $route_match) {
  $x = [
    '```php' => '<code>',
    '```'    => '</code>',
    "\n"     => "\n<br />",
  ];
  switch ($route_name) {
    case 'help.page.pager':
      $txt = file_get_contents(\Drupal::service('extension.list.module')->getPath('pager') . '/README.md');
      return str_replace(array_keys($x), array_values($x), Html::escape($txt));
  }
  return '';
}

/**
 * Implements hook_theme().
 */
function pager_theme() {
  return [
    'pager_block' => [
      'template'  => 'pager--block',
      'variables' => [
        'data' => [],
      ],
    ],
    'pager_wings' => [
      'template'  => 'pager--wings',
      'variables' => [
        'data' => [],
      ],
    ],
  ];
}
