plausible.settings:
  type: config_object
  mapping:
    script:
      type: mapping
      label: 'Script'
      mapping:
        domain:
          type: label
          label: 'Domain'
          translatable: true
        api:
          type: string
          label: 'API endpoint'
        src:
          type: string
          label: 'Script source'
    dashboard:
      type: mapping
      label: 'Dashboard'
      mapping:
        shared_link:
          type: label
          label: 'Shared Link'
          translatable: true
    visibility:
      type: mapping
      label: 'Visibility'
      mapping:
        enable:
          type: boolean
          label: 'Enable tracking'
        admin_route_mode:
          type: integer
          label: 'Add tracking to admin pages'
        request_path_mode:
          type: integer
          label: 'Add tracking to specific pages'
        request_path_pages:
          type: string
          label: 'Pages'
        user_role_roles:
          type: sequence
          label: 'Roles'
          sequence:
            type: string
            label: 'Role enabled'
        user_role_mode:
          type: integer
          label: 'Add tracking for specific roles'
    events:
      type: mapping
      label: 'Events'
      mapping:
        403:
          type: boolean
          label: 'Enable 403 error tracking'
        404:
          type: boolean
          label: 'Enable 404 error tracking'
